### ISSUE TITLE
Use `WebSockets` instead of long-polling

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/artiq-proxy#105]
I found out that `FastAPI` supports not only HTTP protocol, but also `WebSockets`!
(Reference: [FastAPI](https://fastapi.tiangolo.com/advanced/websockets/))

Using this, we don't need to implement long-polling, but just socket communication.

The overall procedure is as following:
1. When IQUIP starts, it connects to ARTIQ-PROXY as a web socket client.
2. Whenever ARTIQ-PROXY detects a modification of datasets or schedule, it sends info to IQUIP.
3. When the socket connection is finished, handle appropriately.

I think it may help the long-polling problems much simpler. What do you think of it? @kangz12345

**Comment by kangz12345** [comment]
That's a great idea to consider using WebSocket protocol! I didn't know what it was.
It looks quite attractive, but I think there is a drawback for datasets:

WebSocket will make too many frame transactions since it will send modification for each dataset update (for each "shot" for the current implementation).
This will burden `iquip` since it must update the plot for each modification.
We have to come up with a proper optimization to resolve this.
Or the long polling could be a simpler solution for the datasets.

Maybe for scheduler, this would not be a problem.

**Comment by BECATRUE** [comment]
We decided to use web sockets to fetch schedule list and datasets, hence I close this issue.
